### ISSUE TITLE
How can I help and take part in your project?

### ISSUE THREAD

**Issue by DmitryAleksandrovich** [titaschanda/QIClib#1]
Hello! I'd like to join your project.
A little about yourself: I'm junior C++ developer, and I don't have commercial development experience. If you have tasks (junior), I'm happy to help project. Sorry with my not very confident English:)

**Comment by titaschanda** [comment]
Hello,
Thank you for your attention in my project.
I am also an amateur C++ developer without any commercial development experience.
Of course, you can help in this project, by reporting any bugs or regressions or by suggesting any new features that can be added to this library. Also you can submit patches of your favorite features/ suggestions  which can be used in any quantum computational tasks.

**Comment by DmitryAleksandrovich** [comment]
Thanks:)
